# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/jayvkothawade@gmail.com/New Pipeline 2025-12-22 13:22")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM spotify_cata.gold.sample_aggregation_dec_22_1322"))

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from spotify_cata.gold.dimuser

# COMMAND ----------

